# Generated by Django 4.1.5 on 2023-01-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_plan', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taked_date', models.DateField()),
                ('taked_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_recharge_backend.rechargeplans')),
            ],
        ),
    ]
