# Generated by Django 4.1.5 on 2023-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplans',
            name='plan_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
